### ISSUE TITLE
Class Search Speed

### ISSUE THREAD

**Issue by RTann** [mrkev/cornell#2]
As cool as the searching with arrow keys is, it gets tedious when the subject you want is in the middle of the alphabet. Anyway to have both arrow key and typed lookup?

**Comment by mrkev** [comment]
for classes: `cornell class [query]`
no search for subjects atm

`cornell class --help` for more info. 😁

**Comment by RTann** [comment]
https://www.youtube.com/watch?v=j74VFngCn7w
